name: Download JS Files

on:
  workflow_dispatch:  # Allows you to manually trigger the action from the GitHub UI
  push:
    paths:             # Run this workflow when there are changes in these specific files
      - 'response4.html'
      - 'download_js_files.py'
      - '.github/workflows/download_js.yml'

jobs:
  download:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set the version of Python to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run script
      run: |
        python download_js_files.py
