name: FlareSolverr Setup and Run

on: [push, pull_request]

jobs:
  setup-and-run:
    runs-on: ubuntu-latest  # Restricts to run only on Ubuntu (Linux)
    steps:
      - name: Checkout FlareSolverr repository
        uses: actions/checkout@v3
        with:
          repository: 'FlareSolverr/FlareSolverr'
          ref: 'main'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FlareSolverr
        run: python src/flaresolverr.py
