name: FlareSolverr Setup and Run

on: [push, pull_request]

jobs:
  setup-and-run:
    runs-on: ubuntu-latest  # Restricts to run only on Ubuntu (Linux)
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Install Git
        run: sudo apt-get update && sudo apt-get install git

      - name: Clone FlareSolverr repository
        run: git clone https://github.com/FlareSolverr/FlareSolverr.git
        working-directory: ${{ github.workspace }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install -r FlareSolverr/requirements.txt

      - name: Run scripts simultaneously
        run: |
          python FlareSolverr/src/flaresolverr.py &
          python scraper.py

