name: FlareSolverr Workflow

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Install req
      run: pip install requests

    - name: Install bs4
      run: pip install beautifulsoup4

    - name: Pull Docker image
      run: docker pull ghcr.io/flaresolverr/flaresolverr:v3.3.17

    - name: Run FlareSolverr
      run: >
        docker run -d --name flaresolverr-container -p 8191:8191
        -e LOG_LEVEL=debug
        --log-driver=json-file --log-opt max-size=50m --log-opt max-file=3
        ghcr.io/flaresolverr/flaresolverr:v3.3.17

    - name: Wait for FlareSolverr to start
      run: sleep 20

    #- name: Fetch container logs 1 (Commented out if not needed)
      #run: timeout 1m docker logs -f flaresolverr-container || true 

    - name: Run Python script
      run: python scraper.py
      
    - name: Fetch container logs 2
      run: timeout 1m docker logs -f flaresolverr-container || true
