name: FlareSolverr Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/flaresolverr/flaresolverr:latest
      env:
        LOG_LEVEL: debug
        LOG_HTML: true
        TZ: Europe/Copenhagen
        BROWSER_TIMEOUT: 200000
        LANG: da_DK

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3
        sudo apt-get install -y python3-pip

    - name: Install req
      run: pip install requests

    - name: Install bs4
      run: pip install beautifulsoup4

    - name: Wait for FlareSolverr to start
      run: sleep 20

    #- name: Fetch container logs 1 (Commented out if not needed)
      #run: timeout 1m docker logs -f flaresolverr-container || true 

    - name: Run Python script
      run: python scraper.py
      
    - name: Fetch container logs 2
      run: docker logs -f ${{ runner.container_id }}
