name: FlareSolverr Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Install req
      run: pip install requests

    - name: Install bs4
      run: pip install beautifulsoup4

    - name: Pull Docker image
      run: docker pull uruknara/flaresolverr:fixlooping
      #run: docker pull ghcr.io/flaresolverr/flaresolverr:latest
      #ghcr.io/flaresolverr/flaresolverr:latest
    - name: Run FlareSolverr container
      run: |
        docker run -d --name flaresolverr-container -p 8191:8191 \
        -e LOG_LEVEL=debug \
        -e LOG_HTML=true \
        -e TZ=Europe/Copenhagen \
        -e BROWSER_TIMEOUT=200000 \
        -e LANG=en_US \
        docker.io/uruknara/flaresolverr:fixlooping

    - name: Wait for FlareSolverr to start
      run: sleep 20

    #- name: Fetch container logs 1 (Commented out if not needed)
      #run: timeout 1m docker logs -f flaresolverr-container || true 

    - name: Run Python script
      run: python scraper.py
      
    - name: Fetch container logs 2
      run: timeout 1m docker logs -f flaresolverr-container || true
